[tool.poetry]
name = "my-django-crm"
version = "0.1.0"
description = "A Django CRM application"

[tool.poetry.dependencies]
python = "^3.6"
django = ">=3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
